export const PLANET_LIST_REQUEST = "PLANET_LIST_REQUEST";
export const PLANET_LIST_SUCCESS = "PLANET_LIST_SUCCESS";
export const PLANET_LIST_FAIL = "PLANET_LIST_FAIL";

export const PLANET_DETAILS_REQUEST = "PLANET_DETAILS_REQUEST";
export const PLANET_DETAILS_SUCCESS = "PLANET_DETAILS_SUCCESS";
export const PLANET_DETAILS_FAIL = "PLANET_DETAILS_FAIL";
